# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=500)),
                ('added_date', models.DateTimeField(verbose_name='added date')),
                ('completed_date', models.DateTimeField(verbose_name='completed date')),
                ('state', models.IntegerField(default=-1)),
            ],
        ),
    ]
