# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='completed_date',
            field=models.DateTimeField(verbose_name='completed_date'),
        ),
    ]
